# NumPy和SciPy

凭借着 NumPy 和 SciPy 提供的高阶数组和矩阵操作，Python 成为科学计算应用的主流语 言。NumPy 实现了多维同质数组(homogeneous array)和矩阵，这些数据结构不但能处理 数字，还能存放其他由用户定义的记录。通过 NumPy，用户能对这些数据结构里的元素进 行高效的操作。

SciPy 是基于 NumPy 的另一个库，它提供了很多跟科学计算有关的算法，专为线性代数、 数值积分和统计学而设计。SciPy 的高效和可靠性归功于其背后的 C 和 Fortran 代码，而这 些跟计算有关的部分都源自于 Netlib 库(http://www.netlib.org)。换句话说，SciPy 把基于 C 和 Fortran 的工业级数学计算功能用交互式且高度抽象的 Python 包装起来，让科学家如 鱼得水。

## 对 numpy.ndarray 的行和列进行基本操作

In [1]:
import numpy as np

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a.shape

(12,)

In [4]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [8]:
a[:, 1]

array([1, 5, 9])

In [10]:
big_array = np.random.randn(1000, 1000)

In [11]:
from time import perf_counter as pc

t0 = pc()
big_array /= 3
pc() - t0

0.0012120900064473972