## Numpy Basic Operations 

In [1]:
import numpy as np

### Build an array of 3 x 4

In [4]:
A = np.arange(2, 14).reshape( (3,4) )
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


### Find min, max element's index

In [40]:
print("Min element's index :", np.argmin(A))
print("Max element's index :", np.argmax(A))
print("Min element's index for each col :", np.argmin(A, axis=0))
print("Max element's index for each col :", np.argmax(A, axis=0))
print("Min element's index for each row :", np.argmin(A, axis=1))
print("Max element's index for each row :", np.argmax(A, axis=1))

Min element's index : 11
Max element's index : 0
Min element's index for each col : [2 2 2 2]
Max element's index for each col : [0 0 0 0]
Min element's index for each row : [3 3 3]
Max element's index for each row : [0 0 0]


### Get mean, average and median

In [14]:
print("Mean    value of array :", np.mean(A))
print("Mean    value of array :", A.mean())
print("Average value of array :", np.average(A))
print("Median  value of array :", np.median(A))

Mean    value of array : 7.5
Mean    value of array : 7.5
Average value of array : 7.5
Median  value of array : 7.5


### Cummulated Sum
Add one by one

In [37]:
print("Original array :", A.reshape(12))
print("Cummulated sum :", A.cumsum())

Original array : [14 13 12 11 10  9  8  7  6  5  4  3]
Cummulated sum : [ 14  27  39  50  60  69  77  84  90  95  99 102]


### Differences between closed elements

In [22]:
print("Original array :\n", A)
print("Diiferent between close elements :\n", np.diff(A))

Original array :
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
Diiferent between close elements :
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


### Non zeros

In [26]:
print("Original array :\n", A)
print("Non zeros's index:", np.nonzero(A))
print("Non zeros's row index: ", np.nonzero(A)[0])
print("Non zeros's col index: ", np.nonzero(A)[0])

Original array :
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
Non zeros's index: (array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
Non zeros's row index:  [0 0 0 0 1 1 1 1 2 2 2 2]
Non zeros's col index:  [0 0 0 0 1 1 1 1 2 2 2 2]


### Sort elements

In [28]:
A = np.arange( 14, 2, -1 ).reshape( ( 3, 4 ) )

In [30]:
print("A : \n", A)
print("Sorted A : \n", np.sort(A))

A : 
 [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
Sorted A : 
 [[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


### Transpoe

In [34]:
print("A : \n", A)
print("Transposed A : \n", np.transpose(A))
print("Transposed A : \n", A.T)

A : 
 [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
Transposed A : 
 [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
Transposed A : 
 [[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


### Clip

In [35]:
print("A : \n", A)
print("A Clipping: \n", np.clip(A, 5, 9) )

A : 
 [[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
A Clipping: 
 [[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
