## Numpy Basic Operations

In [1]:
import numpy as np

### Define 2 array for computations

In [9]:
a = np.array([10,20,30,40])
b = np.arange(1,5)

print("Array a :", a)
print("Array b :", b)

Array a : [10 20 30 40]
Array b : [1 2 3 4]


### Operations on every array element

In [14]:
print("a + b :", a + b)
print("a - b :", a - b)
print("a * b :", a * b)
print("a / b :", a / b)

a + b : [11 22 33 44]
a - b : [ 9 18 27 36]
a * b : [ 10  40  90 160]
a / b : [ 10.  10.  10.  10.]
b ** 2 : [ 1  4  9 16]


In [15]:
print("b ** 2 :", b ** 2)

b ** 2 : [ 1  4  9 16]


In [21]:
print("sin(a) :", np.sin(a))
print("cos(a) :", np.cos(a))
print("tan(b) :", np.tan(b))
print("cot(b) :", 1 / np.tan(b))

sin(a) : [-0.54402111  0.91294525 -0.98803162  0.74511316]
cos(a) : [-0.83907153  0.40808206  0.15425145 -0.66693806]
tan(b) : [ 1.55740772 -2.18503986 -0.14254654  1.15782128]
cot(b) : [ 0.64209262 -0.45765755 -7.01525255  0.86369115]


In [23]:
print("Elements in b < 3 :", b <  3 )
print("Elements in b = 3 :", b == 3 )
print("Elements in b > 3 :", b >  3 )

Elements in b < 3 : [ True  True False False]
Elements in b = 3 : [False False  True False]
Elements in b > 3 : [False False False  True]


### Matrix manipulation

In [26]:
a = a.reshape((2,2))
b = b.reshape((2,2))

print("Reshaped Array a :\n", a)
print("Reshaped Array b :\n", b)

Reshaped Array a :
 [[10 20]
 [30 40]]
Reshaped Array b :
 [[1 2]
 [3 4]]


### Matrix Dot Matrix
- np.dot( *arr_1* , *arr_2* )
- arr_1.dot( *arr_2* )

In [33]:
print("Method 1: a dot b :\n", np.dot(a,b) )
print("Method 2: a dot b :\n", a.dot(b) )

Method 1: a dot b :
 [[ 70 100]
 [150 220]]
Method 2: a dot b :
 [[ 70 100]
 [150 220]]


### Get Min, Max and Sum

In [42]:
a = np.random.random( (2,4) )
print(a)

[[ 0.7189651   0.32518302  0.2703444   0.54595134]
 [ 0.46776028  0.78480763  0.47059151  0.76366503]]


In [43]:
print("Minimum :", np.min(a))
print("Maximum :", np.max(a))
print("Sum     :", np.sum(a))

Minimum : 0.270344400019
Maximum : 0.784807628367
Sum     : 4.3472683051


### Get min, max and sum in axis

In [48]:
# 0 axis -> remove row
print("Minimum in rows :", np.min(a, axis=0))
print("Maximum in rows :", np.max(a, axis=0))
print("Sum     in rows :", np.sum(a, axis=0))

Minimum in rows : [ 0.46776028  0.32518302  0.2703444   0.54595134]
Maximum in rows : [ 0.7189651   0.78480763  0.47059151  0.76366503]
Sum     in rows : [ 1.18672538  1.10999065  0.74093591  1.30961637]


In [47]:
# 1 axis -> remove column
print("Minimum in columns :", np.min(a, axis=1))
print("Maximum in columns :", np.max(a, axis=1))
print("Sum     in columns :", np.sum(a, axis=1))

Minimum in columns : [ 0.2703444   0.46776028]
Maximum in columns : [ 0.7189651   0.78480763]
Sum     in columns : [ 1.86044386  2.48682444]
