## Numpy Create Array

In [1]:
import numpy as np

### Create Array from Python List

np.array(*list*, *dtype*)

In [2]:
a = np.array([[2,3,4],
              [1,2,3]], dtype=np.int)
print(a)

[[2 3 4]
 [1 2 3]]


### Create Zero Matrix

np.zeros( *shape* )

In [3]:
a = np.zeros( (3,4) )  # 3 rows and 4 columns
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


### Create All Ones Matrix

np.ones( *shape* )

In [4]:
a = np.ones( (3,4) )  # 3 rows, 4 columns
print(a)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


### Create Empty Matrix

np.empty( *tuple* )

In [5]:
a = np.empty( (3,4) )
print(a)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


### Create Range

np.arange( *start* , *end* , *step* )

In [6]:
a = np.arange(10, 20, 2)
print(a)

[10 12 14 16 18]


Reshape to get a 3*4 matrix

In [7]:
a = np.arange(12).reshape( (3,4) )
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Create Linspace

np.linspace( *start* , *end* , *num_elements* )

In [8]:
a = np.linspace(1, 10, 6)
print(a)

[  1.    2.8   4.6   6.4   8.2  10. ]


Reshape to 2 * 3

In [9]:
a = np.linspace(1, 10, 6).reshape( (2,3) )
print(a)

[[  1.    2.8   4.6]
 [  6.4   8.2  10. ]]


### Create Random Array

In [10]:
a = np.random.random( (2,4) )
print(a)

[[ 0.30837009  0.45359271  0.31029565  0.70480544]
 [ 0.24704418  0.01325924  0.09738034  0.03416074]]
