## Numpy Operations on Elements Index and Location

In [2]:
import numpy as np

### Create a array for computation 

In [3]:
A = np.arange(3, 15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
print("Third element :", A[2])

Third element : 5


### Two dimensional Array

In [6]:
A = np.arange(3, 15).reshape((3,4))
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [12]:
print("Third element :", A[2])
print("Third element :", A[2, :])
print("Second row, second column's element :", A[1][1])
print("Second row, second column's element :", A[1, 1])
print("Second row, 1-3 elements :", A[1][1:4])
print("Second row, 1-3 elements :", A[1, 1:4])

Third element : [11 12 13 14]
Third element : [11 12 13 14]
Second row, second column's element : 8
Second row, second column's element : 8
Second row, 1-3 elements : [ 8  9 10]
Second row, 1-3 elements : [ 8  9 10]


### Iterate on rows & columns

In [19]:
print("Iterate on rows :")
for row in A:
    print(row)
print("Iterate on cols :")
for col in A.T:
    print(col)

Iterate on rows :
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
Iterate on cols :
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


### Iterate on items

In [34]:
A = np.arange(3, 15).reshape((3,4))
print("Original A :\n", A)
print("Use A.flat to extend to 1 dim :")
for item in A.flat:
    print(item)
print("Use A.flatten() to extend to 1 dim :")
for item in A.flatten():
    print(item)

Original A :
 [[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
Use A.flat to extend to 1 dim :
3
4
5
6
7
8
9
10
11
12
13
14
Use A.flatten() to extend to 1 dim :
3
4
5
6
7
8
9
10
11
12
13
14
